name: Issue Trigger
on:
  issues:
    types: [opened, edited]

jobs:
  test_miniature_octo_sniffle:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Move Issue
        id: api-json
        uses: 100Automations/miniature-octo-sniffle@v0.0.1-alpha

        with:
          # required
          config-file: './.github/workflows/moveIssues/config.json'
          myToken: ${{ secrets.GITHUB_TOKEN }}
          # optional
